### ISSUE TITLE
File to large Exception on Jenkins

### ISSUE THREAD

**Issue by arnzel** [anthavio/phanbedder#1]
Hi.

I tried phanbedder al on my machine and it works well.

On Jenkins i got the following Exception:

java.lang.IllegalStateException: Failed to unpack resource: linux64/phantomjs into: /tmp/phantomjs-1.9.8/phantomjs
    at net.anthavio.phanbedder.Phanbedder.unpack(Phanbedder.java:139)
    at net.anthavio.phanbedder.Phanbedder.unpack(Phanbedder.java:101)
    at net.anthavio.phanbedder.Phanbedder.unpack(Phanbedder.java:55)
    at ebayKleinanzeigen.selenium.TestCreateAnzeigeBieteNachhilfe.setupGhostDriver(TestCreateAnzeigeBieteNachhilfe.java:39)
    at ebayKleinanzeigen.selenium.TestCreateAnzeigeBieteNachhilfe.setUp(TestCreateAnzeigeBieteNachhilfe.java:33)
    at junit.framework.TestCase.runBare(TestCase.java:139)
    at junit.framework.TestResult$1.protect(TestResult.java:122)
    at junit.framework.TestResult.runProtected(TestResult.java:142)
    at junit.framework.TestResult.run(TestResult.java:125)
    at junit.framework.TestCase.run(TestCase.java:129)
    at junit.framework.TestSuite.runTest(TestSuite.java:255)
    at junit.framework.TestSuite.run(TestSuite.java:250)
    at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)
    at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
    at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
    at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
    at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
    at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.io.IOException: Die Datei ist zu groß
    at java.io.FileOutputStream.writeBytes(Native Method)
    at java.io.FileOutputStream.write(FileOutputStream.java:345)
    at java.io.BufferedOutputStream.write(BufferedOutputStream.java:122)
    at java.io.FilterOutputStream.write(FilterOutputStream.java:97)
    at net.anthavio.phanbedder.Phanbedder.unpack(Phanbedder.java:134)

**Comment by anthavio** [comment]
Wow. German localized error message. Only what I was able to Google out is something related to FAT32 filesystem
http://forum.computerbild.de/pc-hardware/datei-verschieben-datei-gross-fuer-zielsystem_15708.html
or maybe simply full disk? Linux binaries of phantomjs are about 38 megabytes.

**Comment by arnzel** [comment]
Hi. My Server has 300 MB, should be enough of ?

Fat32 has a limit of 4gb. So 38 MB should be not the Problem or ?

**Comment by miere** [comment]
Hi @arnzel 
Did you already solve the problem?
If you didn't solve it yet. Could you please send more details about your Jenkins environment.
